apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rabbitconsumer
spec:
  selector:
    matchLabels:
      app: rabbitconsumer
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitconsumer
    spec:
      containers:
      - image: gcr.io/ssuuuu-222721/consumer/rabbit
        name: rabbitconsumer
        env:
        - name: STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: storage-bucket
        - name: CASSANDRA_DB
          value: "cassandra"
