apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
  - port: 9042
  selector:
    app: cassandra
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - image: cassandra:3.11.3
        name: cassandra
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: instagram
        ports:
        - containerPort: 7000
          name: intranode
        - containerPort: 7001
          name: tls
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
