apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rabbitconsumer
spec:
  selector:
    matchLabels:
      app: rabbitconsumer
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitconsumer
    spec:
      containers:
      - image: gcr.io/ssuuuu-222721/rabbit_consumer
        name: rabbitconsumer
        env:
        - name: RABBITMQ_SERVICE_SERVICE_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_SERVICE_SERVICE_PORT
          value: "5672"
        - name: CASSANDRA_DB
          value: "cassandra"
