apiVersion: v1
kind: Pod
metadata:
  name: content-writer
spec:
  containers:
  - name: content-writer
    image: gcr.io/ssuuuu-222721/content/writer
    env:
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: secrets
          key: jwt-secret
    - name: STORAGE_BUCKET
      valueFrom:
        secretKeyRef:
          name: secrets
          key: storage-bucket
