apiVersion: v1
kind: Pod
metadata:
  name: content-writer
spec:
  containers:
  - name: content-writer
    image: content-writer
    env:
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
