apiVersion: v1
kind: Pod
metadata:
  name: content-writer
spec:
  containers:
  - name: content-writer
    image: gcr.io/cs385fa18/content-writer
    env:
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: jwt-secret
          key: secret
    - name: STORAGE_BUCKET
      value: 385ig
